version: '3'
services:
  api-server:
    image: speculatingwook/api-server:20241225172718
    ports:
      - "8080:8080"
    volumes:
      - ./resona-bucket-private-key.pem:/app/keys/resona-bucket-private-key.pem
    env_file:
      - .env
    environment:
      - JAVA_OPTS=-Xms128m -Xmx512m
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=https://resona.life/prometheus"
      - "--web.route-prefix=/"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "1001:1001"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=resona.life
      - GF_SERVER_ENFORCE_DOMAIN=false
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_APP_URL=https://resona.life/grafana