server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://atch-database-1.c52esqc6awjk.us-east-2.rds.amazonaws.com:3306/dev?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: atchAdmin
    password: 2024atchletsgo

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 500
    #        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
#        database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database: mysql
    #open-in-view: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher
# cors 설정
cors:
  allowed-origins: 'http://ec2-16-171-110-180.eu-north-1.compute.amazonaws.com:8080'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

jwt:
  secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

aws:
  access-key: AKIATCKAQGU54KZHFK7Q
  secret-key: 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
  region: us-east-2