server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: prod
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      authentication-database: ${MONGO_AUTH_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
#      database:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
#        format_sql: true
        default_batch_fetch_size: 500
#        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    #        database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
#    database: mysql
    open-in-view: false

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  security:
    oauth2.client:
      registration:
        google:
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile
jwt.secret: ${JWT_SECRET}

# cors 설정
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGIN}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600


# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: ${AUTH_TOKEN_SECRET}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ${REGION}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

