spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  data:
    redis:
    mongodb:
  mail:
    host: localhost
    port: 25

jwt:
  secret: "this-is-a-dummy-jwt-secret-for-testing-purpose-only"

app:
  auth:
    tokenSecret: "this-is-a-dummy-auth-token-secret-for-testing"

fcm:
  path: "/dev/null"

oci:
  config:
    privateKeyPath: "/dev/null"