SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE member_provider;
TRUNCATE TABLE follow;
TRUNCATE TABLE block;
TRUNCATE TABLE comment_likes;
TRUNCATE TABLE likes;
TRUNCATE TABLE scrap;
TRUNCATE TABLE report;
TRUNCATE TABLE mention;
TRUNCATE TABLE comment;
TRUNCATE TABLE feed;
TRUNCATE TABLE member;
TRUNCATE TABLE account_info;
TRUNCATE TABLE member_details;
TRUNCATE TABLE profile;

SET REFERENTIAL_INTEGRITY TRUE;