name: Spring Boot & Gradle & Docker & EC2 CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}  # 'timestamp' 값을 outputs로 설정
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Build Docker Image For Spring
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ steps.timestamp.outputs.timestamp }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t $DOCKER_USERNAME/api-server:$IMAGE_TAG .
          docker push $DOCKER_USERNAME/api-server:$IMAGE_TAG
          docker tag $DOCKER_USERNAME/api-server:$IMAGE_TAG $DOCKER_USERNAME/api-server:latest
          docker push $DOCKER_USERNAME/api-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 'build' job이 완료된 후에 'deploy' job 실행
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            echo "${{ secrets.ENV_PROD_FILE }}" | base64 --decode > .env

            # Debugging: Check Docker Username and Image Tag
            echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"
            echo "Image Tag: ${{ needs.build.outputs.timestamp }}"  # 'needs'를 사용하여 build job의 출력 참조

            # 기존 api-server 컨테이너 중지 및 제거 (api-server만 대상으로 함)
            if [ $(docker ps -q -f name=api-server) ]; then
              echo "Stopping and removing existing api-server container..."
              docker rm -f api-server
            fi

            # Pulling the image
            docker pull ${{ secrets.DOCKER_USERNAME }}/api-server:${{ needs.build.outputs.timestamp }}

            # Check if the image was successfully pulled
            docker images

            # Running the container
            docker run --name api-server -d --network synapps -p 8080:8080 --env-file .env ${{ secrets.DOCKER_USERNAME }}/api-server:${{ needs.build.outputs.timestamp }}

      - name: Health Check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Waiting for application to start..."
            for i in {1..15}
            do
              if curl -sSf http://localhost:8080/api/v1/actuator/health > /dev/null 2>&1
              then
                echo "Application is healthy"
                exit 0
              fi
              echo "Attempt $i: Application is not yet healthy. Waiting..."
              sleep 10
            done
            echo "Application failed to become healthy within timeout"
            docker logs api-server
            exit 1

      - name: Rollback on Failure
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deployment failed, rolling back..."

            # 현재 실패한 이미지의 timestamp를 저장
            FAILED_TAG=${{ steps.timestamp.outputs.timestamp }}

            # 실패한 이미지를 삭제
            docker rmi ${{ secrets.DOCKER_USERNAME }}/api-server:$FAILED_TAG || true

            # 가장 큰 timestamp 태그를 가진 이미지를 찾음
            LAST_SUCCESSFUL_TAG=$(docker images --format "{{.Tag}}" | grep -E '^[0-9]{14}$' | sort -r | head -n 1)

            # 해당 이미지를 실행
            docker pull ${{ secrets.DOCKER_USERNAME }}/api-server:$LAST_SUCCESSFUL_TAG
            docker run --network synapps -d --name api-server -p 8080:8080 --env-file .env ${{ secrets.DOCKER_USERNAME }}/api-server:$LAST_SUCCESSFUL_TAG
            echo "Rollback to $LAST_SUCCESSFUL_TAG completed"
